version: '3'
networks:
    waiting_for_conteiner:
services:
    newrabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
    web:
        build:
            dockerfile: rest.Dockerfile
            context: .
        command: uvicorn main:app --reload
        ports:
            - "8000:8000"
        depends_on:
            - newrabbitmq

    conteiner_cunsumer:
        build:
            dockerfile: consum.Dockerfile
            context: .
        container_name: conteiner_cunsumer
        command: python3 /project/consumer/consumer.py
        restart: "no"
        networks:
            - waiting_for_conteiner
        depends_on:
            - web