version: '3'
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        networks:
            - deployml_network
        ports:
            - 5672:5672
    web:
        build:
            dockerfile: rest.Dockerfile
            context: ./testrest
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        environment:
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
        networks:
            - deployml_network
        ports:
            - "8000:8000"
        depends_on:
            - rabbitmq

    conteiner_cunsumer:
        build:
            dockerfile: consum.Dockerfile
            context: ./consumer
        command: python3 /app/consumer.py
        environment:
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
        networks:
            - deployml_network
        restart: "always"
        depends_on:
            - rabbitmq
networks:
    deployml_network: