version: '3.4'
networks:
  app-tier:
    driver: bridge
services:
    newrabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        networks:
            - app-tier
        ports:
            - "5672:5672"
            - "15672:15672"
    web:
        build:
            dockerfile: rest.Dockerfile
            context: .
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        networks:
            - app-tier
        ports:
            - "8000:8000"
        depends_on:
            - newrabbitmq

    conteiner_cunsumer:
        build:
            dockerfile: consum.Dockerfile
            context: .
        container_name: conteiner_cunsumer
        command: python3 /project/consumer/consumer.py
        restart: "always"
        networks:
            - app-tier
        depends_on:
            - web